<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUa7exn7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUa7exn7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUa7exn7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUa7exn7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUa7exn7\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ua7exn7',
    'container.build_id' => 'b9f5a85f',
    'container.build_time' => 1522314914,
));
